package sqlite

import (
	"context"
	"database/sql"
	"encoding/json"
	"errors"
	"time"

	"github.com/Methamorphe/go-agent/internal/errs"
	"github.com/Methamorphe/go-agent/internal/id"
	"github.com/Methamorphe/go-agent/internal/orchestration"
)

func orchestrationJSON(v any) (string, error) { body, err := json.Marshal(v); return string(body), err }

func (s *Store) BootstrapRoot(ctx context.Context, agentID id.AgentID, policy orchestration.RootPolicy, now time.Time) error {
	auth,_:=orchestrationJSON(policy.Authority); avail,_:=orchestrationJSON(policy.Budget); reserved,_:=orchestrationJSON(orchestration.Budget{}); policyJSON,_:=orchestrationJSON(policy)
	_,err:=s.db.ExecContext(ctx,`INSERT INTO orchestration_accounts(agent_id,root_id,authority_json,available_json,reserved_json,policy_json,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(agent_id) DO NOTHING`,agentID.String(),agentID.String(),auth,avail,reserved,policyJSON,formatTime(now),formatTime(now))
	if err!=nil{return errs.Wrap(errs.CodeUnavailable,"sqlite.orchestration.bootstrap","insert root account",err)};return nil
}

func scanOrchestrationAccount(scanner rowScanner)(orchestration.Account,error){var a orchestration.Account;var aid,rid,auth,avail,reserved,policy string;if err:=scanner.Scan(&aid,&rid,&auth,&avail,&reserved,&policy);err!=nil{return a,err};a.AgentID=id.AgentID(aid);a.RootID=id.AgentID(rid);if err:=json.Unmarshal([]byte(auth),&a.Authority);err!=nil{return a,err};if err:=json.Unmarshal([]byte(avail),&a.Available);err!=nil{return a,err};if err:=json.Unmarshal([]byte(reserved),&a.Reserved);err!=nil{return a,err};if err:=json.Unmarshal([]byte(policy),&a.Policy);err!=nil{return a,err};return a,nil}
func (s *Store) Account(ctx context.Context,agentID id.AgentID)(orchestration.Account,error){a,err:=scanOrchestrationAccount(s.db.QueryRowContext(ctx,`SELECT agent_id,root_id,authority_json,available_json,reserved_json,policy_json FROM orchestration_accounts WHERE agent_id=?`,agentID.String()));if errors.Is(err,sql.ErrNoRows){return a,errs.Wrap(errs.CodeNotFound,"sqlite.orchestration.account","account not found",err)};if err!=nil{return a,errs.Wrap(errs.CodeUnavailable,"sqlite.orchestration.account","query account",err)};return a,nil}

func (s *Store) ReserveSpawn(ctx context.Context,r orchestration.SpawnRecord)error{
	tx,err:=s.db.BeginTx(ctx,nil);if err!=nil{return err};defer tx.Rollback();a,err:=scanOrchestrationAccount(tx.QueryRowContext(ctx,`SELECT agent_id,root_id,authority_json,available_json,reserved_json,policy_json FROM orchestration_accounts WHERE agent_id=?`,r.ParentAgentID.String()));if err!=nil{return err};if !r.Reserved.Fits(a.Available){return errs.New(errs.CodeResourceExhausted,"sqlite.orchestration.reserve","budget no longer available")};a.Available=a.Available.Sub(r.Reserved);a.Reserved=a.Reserved.Add(r.Reserved);avail,_:=orchestrationJSON(a.Available);reserved,_:=orchestrationJSON(a.Reserved);auth,_:=orchestrationJSON(r.Authority);budget,_:=orchestrationJSON(r.Reserved);resultContract,_:=orchestrationJSON(r.Result)
	if _,err=tx.ExecContext(ctx,`UPDATE orchestration_accounts SET available_json=?,reserved_json=?,updated_at=? WHERE agent_id=?`,avail,reserved,formatTime(r.UpdatedAt),r.ParentAgentID.String());err!=nil{return err}
	if _,err=tx.ExecContext(ctx,`INSERT INTO orchestration_spawns(spawn_id,parent_agent_id,root_agent_id,depth,task_intent,task_key,authority_json,reservation_id,reserved_json,result_contract_json,deadline,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)`,r.ID.String(),r.ParentAgentID.String(),r.RootAgentID.String(),r.Depth,r.TaskIntent,r.TaskKey,auth,r.ReservationID.String(),budget,resultContract,formatOptionalTime(r.Deadline),string(r.Status),formatTime(r.CreatedAt),formatTime(r.UpdatedAt));err!=nil{return err};return tx.Commit()
}

func (s *Store) BindSpawnChild(ctx context.Context,spawnID id.SpawnID,childID id.AgentID,now time.Time)error{tx,err:=s.db.BeginTx(ctx,nil);if err!=nil{return err};defer tx.Rollback();r,err:=scanOrchestrationSpawn(tx.QueryRowContext(ctx,orchestrationSpawnSelect+` WHERE spawn_id=?`,spawnID.String()));if err!=nil{return err};parent,err:=scanOrchestrationAccount(tx.QueryRowContext(ctx,`SELECT agent_id,root_id,authority_json,available_json,reserved_json,policy_json FROM orchestration_accounts WHERE agent_id=?`,r.ParentAgentID.String()));if err!=nil{return err};auth,_:=orchestrationJSON(r.Authority);available,_:=orchestrationJSON(r.Reserved);zero,_:=orchestrationJSON(orchestration.Budget{});policy,_:=orchestrationJSON(parent.Policy);if _,err=tx.ExecContext(ctx,`INSERT INTO orchestration_accounts(agent_id,root_id,authority_json,available_json,reserved_json,policy_json,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)`,childID.String(),r.RootAgentID.String(),auth,available,zero,policy,formatTime(now),formatTime(now));err!=nil{return err};res,err:=tx.ExecContext(ctx,`UPDATE orchestration_spawns SET child_agent_id=?,status=?,updated_at=? WHERE spawn_id=? AND status=?`,childID.String(),string(orchestration.SpawnCreated),formatTime(now),spawnID.String(),string(orchestration.SpawnReserved));if err!=nil{return err};n,_:=res.RowsAffected();if n!=1{return errs.New(errs.CodeConflict,"sqlite.orchestration.bind","spawn is no longer reserved")};return tx.Commit()}
func (s *Store) RejectSpawn(ctx context.Context,spawnID id.SpawnID,reason string,now time.Time)error{tx,err:=s.db.BeginTx(ctx,nil);if err!=nil{return err};defer tx.Rollback();r,err:=scanOrchestrationSpawn(tx.QueryRowContext(ctx,orchestrationSpawnSelect+` WHERE spawn_id=?`,spawnID.String()));if err!=nil{return err};if r.Status!=orchestration.SpawnReserved{return nil};a,err:=scanOrchestrationAccount(tx.QueryRowContext(ctx,`SELECT agent_id,root_id,authority_json,available_json,reserved_json,policy_json FROM orchestration_accounts WHERE agent_id=?`,r.ParentAgentID.String()));if err!=nil{return err};a.Available=a.Available.Add(r.Reserved);a.Reserved=a.Reserved.Sub(r.Reserved);avail,_:=orchestrationJSON(a.Available);reserved,_:=orchestrationJSON(a.Reserved);if _,err=tx.ExecContext(ctx,`UPDATE orchestration_accounts SET available_json=?,reserved_json=?,updated_at=? WHERE agent_id=?`,avail,reserved,formatTime(now),a.AgentID.String());err!=nil{return err};if _,err=tx.ExecContext(ctx,`UPDATE orchestration_spawns SET status=?,reject_reason=?,updated_at=? WHERE spawn_id=?`,string(orchestration.SpawnRejected),reason,formatTime(now),spawnID.String());err!=nil{return err};return tx.Commit()}
func (s *Store) SettleSpawn(ctx context.Context,spawnID id.SpawnID,actual orchestration.Budget,now time.Time)error{tx,err:=s.db.BeginTx(ctx,nil);if err!=nil{return err};defer tx.Rollback();r,err:=scanOrchestrationSpawn(tx.QueryRowContext(ctx,orchestrationSpawnSelect+` WHERE spawn_id=?`,spawnID.String()));if err!=nil{return err};if r.Status==orchestration.SpawnSettled{return nil};if r.Status!=orchestration.SpawnCreated{return errs.New(errs.CodeConflict,"sqlite.orchestration.settle","spawn is not created")};if !actual.Fits(r.Reserved){return errs.New(errs.CodeResourceExhausted,"sqlite.orchestration.settle","actual exceeds reservation")};a,err:=scanOrchestrationAccount(tx.QueryRowContext(ctx,`SELECT agent_id,root_id,authority_json,available_json,reserved_json,policy_json FROM orchestration_accounts WHERE agent_id=?`,r.ParentAgentID.String()));if err!=nil{return err};unused:=r.Reserved.Sub(actual);a.Reserved=a.Reserved.Sub(r.Reserved);a.Available=a.Available.Add(unused);avail,_:=orchestrationJSON(a.Available);reserved,_:=orchestrationJSON(a.Reserved);actualJSON,_:=orchestrationJSON(actual);if _,err=tx.ExecContext(ctx,`UPDATE orchestration_accounts SET available_json=?,reserved_json=?,updated_at=? WHERE agent_id=?`,avail,reserved,formatTime(now),a.AgentID.String());err!=nil{return err};if _,err=tx.ExecContext(ctx,`UPDATE orchestration_spawns SET status=?,actual_json=?,updated_at=? WHERE spawn_id=?`,string(orchestration.SpawnSettled),actualJSON,formatTime(now),spawnID.String());err!=nil{return err};return tx.Commit()}

const orchestrationSpawnSelect=`SELECT spawn_id,parent_agent_id,COALESCE(child_agent_id,''),root_agent_id,depth,task_intent,task_key,authority_json,reservation_id,reserved_json,result_contract_json,deadline,status,created_at,updated_at FROM orchestration_spawns`
func scanOrchestrationSpawn(scanner rowScanner)(orchestration.SpawnRecord,error){var r orchestration.SpawnRecord;var sid,pid,cid,rid,auth,reservation,budget,resultContract,status,created,updated string;var deadline sql.NullString;if err:=scanner.Scan(&sid,&pid,&cid,&rid,&r.Depth,&r.TaskIntent,&r.TaskKey,&auth,&reservation,&budget,&resultContract,&deadline,&status,&created,&updated);err!=nil{return r,err};r.ID=id.SpawnID(sid);r.ParentAgentID=id.AgentID(pid);r.ChildAgentID=id.AgentID(cid);r.RootAgentID=id.AgentID(rid);r.ReservationID=id.BudgetReservationID(reservation);r.Status=orchestration.SpawnStatus(status);if err:=json.Unmarshal([]byte(auth),&r.Authority);err!=nil{return r,err};if err:=json.Unmarshal([]byte(budget),&r.Reserved);err!=nil{return r,err};if err:=json.Unmarshal([]byte(resultContract),&r.Result);err!=nil{return r,err};var err error;if deadline.Valid{v,parseErr:=time.Parse(time.RFC3339Nano,deadline.String);if parseErr!=nil{return r,parseErr};r.Deadline=&v};r.CreatedAt,err=time.Parse(time.RFC3339Nano,created);if err!=nil{return r,err};r.UpdatedAt,err=time.Parse(time.RFC3339Nano,updated);return r,err}
func (s *Store) Spawn(ctx context.Context,spawnID id.SpawnID)(orchestration.SpawnRecord,error){r,err:=scanOrchestrationSpawn(s.db.QueryRowContext(ctx,orchestrationSpawnSelect+` WHERE spawn_id=?`,spawnID.String()));if errors.Is(err,sql.ErrNoRows){return r,errs.Wrap(errs.CodeNotFound,"sqlite.orchestration.spawn","spawn not found",err)};return r,err}
func (s *Store) FindReusableSpawn(ctx context.Context,root id.AgentID,key string)(orchestration.SpawnRecord,bool,error){r,err:=scanOrchestrationSpawn(s.db.QueryRowContext(ctx,orchestrationSpawnSelect+` WHERE root_agent_id=? AND task_key=? AND status=? ORDER BY updated_at DESC LIMIT 1`,root.String(),key,string(orchestration.SpawnSettled)));if errors.Is(err,sql.ErrNoRows){return r,false,nil};return r,err==nil,err}
func (s *Store) CountChildren(ctx context.Context,parent id.AgentID)(int,error){var n int;err:=s.db.QueryRowContext(ctx,`SELECT COUNT(*) FROM orchestration_spawns WHERE parent_agent_id=? AND status IN (?,?)`,parent.String(),string(orchestration.SpawnCreated),string(orchestration.SpawnSettled)).Scan(&n);return n,err}
func (s *Store) CountDescendants(ctx context.Context,root id.AgentID)(int,error){var n int;err:=s.db.QueryRowContext(ctx,`WITH RECURSIVE d(agent_id) AS (SELECT child_agent_id FROM orchestration_spawns WHERE parent_agent_id=? AND child_agent_id IS NOT NULL AND status IN (?,?) UNION ALL SELECT s.child_agent_id FROM orchestration_spawns s JOIN d ON s.parent_agent_id=d.agent_id WHERE s.child_agent_id IS NOT NULL AND s.status IN (?,?)) SELECT COUNT(*) FROM d`,root.String(),string(orchestration.SpawnCreated),string(orchestration.SpawnSettled),string(orchestration.SpawnCreated),string(orchestration.SpawnSettled)).Scan(&n);return n,err}
func (s *Store) Descendants(ctx context.Context,root id.AgentID)([]id.AgentID,error){rows,err:=s.db.QueryContext(ctx,`WITH RECURSIVE d(agent_id,depth) AS (SELECT child_agent_id,1 FROM orchestration_spawns WHERE parent_agent_id=? AND child_agent_id IS NOT NULL UNION ALL SELECT s.child_agent_id,d.depth+1 FROM orchestration_spawns s JOIN d ON s.parent_agent_id=d.agent_id WHERE s.child_agent_id IS NOT NULL) SELECT agent_id FROM d ORDER BY depth DESC,agent_id`,root.String());if err!=nil{return nil,err};defer rows.Close();var out []id.AgentID;for rows.Next(){var v string;if err:=rows.Scan(&v);err!=nil{return nil,err};out=append(out,id.AgentID(v))};return out,rows.Err()}
