package sqlite

import (
	"context"
	"database/sql"
	"encoding/json"
	"errors"
	"sort"
	"time"

	"github.com/Methamorphe/go-agent/internal/errs"
	"github.com/Methamorphe/go-agent/internal/id"
	"github.com/Methamorphe/go-agent/internal/orchestration"
)

func jsonText(v any) (string, error) { b, err := json.Marshal(v); return string(b), err }

func (s *Store) BootstrapRoot(ctx context.Context, agentID id.AgentID, policy orchestration.RootPolicy, now time.Time) error {
	auth, err := jsonText(policy.Authority); if err != nil { return err }
	budget, err := jsonText(policy.Budget); if err != nil { return err }
	zero, _ := jsonText(orchestration.Budget{})
	policyJSON, err := jsonText(policy); if err != nil { return err }
	_, err = s.db.ExecContext(ctx, `INSERT INTO orchestration_accounts(agent_id,root_id,authority_json,available_json,reserved_json,policy_json,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(agent_id) DO NOTHING`, agentID.String(), agentID.String(), auth, budget, zero, policyJSON, formatTime(now), formatTime(now))
	if err != nil { return errs.Wrap(errs.CodeUnavailable, "sqlite.orchestration.bootstrap", "insert root account", err) }
	return nil
}

func scanAccount(row rowScanner) (orchestration.Account, error) {
	var a orchestration.Account; var agent, root, auth, avail, reserved, policy string
	if err := row.Scan(&agent,&root,&auth,&avail,&reserved,&policy); err != nil { return a, err }
	a.AgentID=id.AgentID(agent); a.RootID=id.AgentID(root)
	if err:=json.Unmarshal([]byte(auth),&a.Authority); err!=nil{return a,err}; if err:=json.Unmarshal([]byte(avail),&a.Available);err!=nil{return a,err}; if err:=json.Unmarshal([]byte(reserved),&a.Reserved);err!=nil{return a,err}; if err:=json.Unmarshal([]byte(policy),&a.Policy);err!=nil{return a,err}
	return a,nil
}

func (s *Store) Account(ctx context.Context, agentID id.AgentID) (orchestration.Account,error) {
	a,err:=scanAccount(s.db.QueryRowContext(ctx,`SELECT agent_id,root_id,authority_json,available_json,reserved_json,policy_json FROM orchestration_accounts WHERE agent_id=?`,agentID.String()))
	if errors.Is(err,sql.ErrNoRows){return a,errs.Wrap(errs.CodeNotFound,"sqlite.orchestration.account","account not found",err)}; if err!=nil{return a,errs.Wrap(errs.CodeUnavailable,"sqlite.orchestration.account","query account",err)}; return a,nil
}

func (s *Store) ReserveSpawn(ctx context.Context, record orchestration.SpawnRecord) error {
	tx,err:=s.db.BeginTx(ctx,nil); if err!=nil{return errs.Wrap(errs.CodeUnavailable,"sqlite.orchestration.reserve","begin",err)}; defer tx.Rollback()
	a,err:=scanAccount(tx.QueryRowContext(ctx,`SELECT agent_id,root_id,authority_json,available_json,reserved_json,policy_json FROM orchestration_accounts WHERE agent_id=?`,record.ParentAgentID.String())); if err!=nil{return errs.Wrap(errs.CodeUnavailable,"sqlite.orchestration.reserve","load parent account",err)}
	if !record.Reserved.Fits(a.Available){return errs.New(errs.CodeResourceExhausted,"sqlite.orchestration.reserve","budget no longer available")}
	a.Available=a.Available.Sub(record.Reserved); a.Reserved=a.Reserved.Add(record.Reserved)
	avail,_:=jsonText(a.Available); reserved,_:=jsonText(a.Reserved); auth,_:=jsonText(record.Authority); rb,_:=jsonText(record.Reserved)
	if _,err=tx.ExecContext(ctx,`UPDATE orchestration_accounts SET available_json=?,reserved_json=?,updated_at=? WHERE agent_id=?`,avail,reserved,formatTime(record.UpdatedAt),record.ParentAgentID.String());err!=nil{return errs.Wrap(errs.CodeUnavailable,"sqlite.orchestration.reserve","debit parent",err)}
	_,err=tx.ExecContext(ctx,`INSERT INTO orchestration_spawns(spawn_id,parent_agent_id,root_agent_id,depth,task_intent,task_key,authority_json,reservation_id,reserved_json,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)`,record.ID.String(),record.ParentAgentID.String(),record.RootAgentID.String(),record.Depth,record.TaskIntent,record.TaskKey,auth,record.ReservationID.String(),rb,string(record.Status),formatTime(record.CreatedAt),formatTime(record.UpdatedAt)); if err!=nil{return errs.Wrap(errs.CodeUnavailable,"sqlite.orchestration.reserve","insert spawn",err)}
	if err=tx.Commit();err!=nil{return errs.Wrap(errs.CodeUnavailable,"sqlite.orchestration.reserve","commit",err)}; return nil
}

func (s *Store) BindSpawnChild(ctx context.Context, spawnID id.SpawnID, childID id.AgentID, now time.Time) error {
	tx,err:=s.db.BeginTx(ctx,nil);if err!=nil{return err};defer tx.Rollback()
	record,err:=scanSpawn(tx.QueryRowContext(ctx,`SELECT spawn_id,parent_agent_id,child_agent_id,root_agent_id,depth,task_intent,task_key,authority_json,reservation_id,reserved_json,status,created_at,updated_at FROM orchestration_spawns WHERE spawn_id=?`,spawnID.String()));if err!=nil{return err}
	parent,err:=scanAccount(tx.QueryRowContext(ctx,`SELECT agent_id,root_id,authority_json,available_json,reserved_json,policy_json FROM orchestration_accounts WHERE agent_id=?`,record.ParentAgentID.String()));if err!=nil{return err}
	auth,_:=jsonText(record.Authority); budget,_:=jsonText(record.Reserved); zero,_:=jsonText(orchestration.Budget{}); policy,_:=jsonText(parent.Policy)
	if _,err=tx.ExecContext(ctx,`INSERT INTO orchestration_accounts(agent_id,root_id,authority_json,available_json,reserved_json,policy_json,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)`,childID.String(),record.RootAgentID.String(),auth,budget,zero,policy,formatTime(now),formatTime(now));err!=nil{return errs.Wrap(errs.CodeUnavailable,"sqlite.orchestration.bind","create child account",err)}
	if _,err=tx.ExecContext(ctx,`UPDATE orchestration_spawns SET child_agent_id=?,status=?,updated_at=? WHERE spawn_id=? AND status=?`,childID.String(),string(orchestration.SpawnCreated),formatTime(now),spawnID.String(),string(orchestration.SpawnReserved));err!=nil{return errs.Wrap(errs.CodeUnavailable,"sqlite.orchestration.bind","bind child",err)}
	return tx.Commit()
}

func (s *Store) RejectSpawn(ctx context.Context, spawnID id.SpawnID, reason string, now time.Time) error {
	tx,err:=s.db.BeginTx(ctx,nil);if err!=nil{return err};defer tx.Rollback(); record,err:=scanSpawn(tx.QueryRowContext(ctx,`SELECT spawn_id,parent_agent_id,child_agent_id,root_agent_id,depth,task_intent,task_key,authority_json,reservation_id,reserved_json,status,created_at,updated_at FROM orchestration_spawns WHERE spawn_id=?`,spawnID.String()));if err!=nil{return err};if record.Status!=orchestration.SpawnReserved{return nil}
	a,err:=scanAccount(tx.QueryRowContext(ctx,`SELECT agent_id,root_id,authority_json,available_json,reserved_json,policy_json FROM orchestration_accounts WHERE agent_id=?`,record.ParentAgentID.String()));if err!=nil{return err};a.Available=a.Available.Add(record.Reserved);a.Reserved=a.Reserved.Sub(record.Reserved);av,_:=jsonText(a.Available);rv,_:=jsonText(a.Reserved)
	if _,err=tx.ExecContext(ctx,`UPDATE orchestration_accounts SET available_json=?,reserved_json=?,updated_at=? WHERE agent_id=?`,av,rv,formatTime(now),a.AgentID.String());err!=nil{return err};if _,err=tx.ExecContext(ctx,`UPDATE orchestration_spawns SET status=?,reject_reason=?,updated_at=? WHERE spawn_id=?`,string(orchestration.SpawnRejected),reason,formatTime(now),spawnID.String());err!=nil{return err};return tx.Commit()
}

func (s *Store) SettleSpawn(ctx context.Context, spawnID id.SpawnID, actual orchestration.Budget, now time.Time) error {
	tx,err:=s.db.BeginTx(ctx,nil);if err!=nil{return err};defer tx.Rollback();record,err:=scanSpawn(tx.QueryRowContext(ctx,`SELECT spawn_id,parent_agent_id,child_agent_id,root_agent_id,depth,task_intent,task_key,authority_json,reservation_id,reserved_json,status,created_at,updated_at FROM orchestration_spawns WHERE spawn_id=?`,spawnID.String()));if err!=nil{return err};if record.Status==orchestration.SpawnSettled{return nil};if record.Status!=orchestration.SpawnCreated{return errs.New(errs.CodeConflict,"sqlite.orchestration.settle","spawn is not created")};if !actual.Fits(record.Reserved){return errs.New(errs.CodeResourceExhausted,"sqlite.orchestration.settle","actual exceeds reservation")}
	a,err:=scanAccount(tx.QueryRowContext(ctx,`SELECT agent_id,root_id,authority_json,available_json,reserved_json,policy_json FROM orchestration_accounts WHERE agent_id=?`,record.ParentAgentID.String()));if err!=nil{return err};unused:=record.Reserved.Sub(actual);a.Reserved=a.Reserved.Sub(record.Reserved);a.Available=a.Available.Add(unused);av,_:=jsonText(a.Available);rv,_:=jsonText(a.Reserved);act,_:=jsonText(actual)
	if _,err=tx.ExecContext(ctx,`UPDATE orchestration_accounts SET available_json=?,reserved_json=?,updated_at=? WHERE agent_id=?`,av,rv,formatTime(now),a.AgentID.String());err!=nil{return err};if _,err=tx.ExecContext(ctx,`UPDATE orchestration_spawns SET status=?,actual_json=?,updated_at=? WHERE spawn_id=?`,string(orchestration.SpawnSettled),act,formatTime(now),spawnID.String());err!=nil{return err};return tx.Commit()
}

type spawnScanner interface{ Scan(...any) error }
func scanSpawn(row spawnScanner)(orchestration.SpawnRecord,error){var r orchestration.SpawnRecord;var sid,parent,child,root,taskKey,auth,resID,reserved,status,created,updated string;err:=row.Scan(&sid,&parent,&child,&root,&r.Depth,&r.TaskIntent,&taskKey,&auth,&resID,&reserved,&status,&created,&updated);if err!=nil{return r,err};r.ID=id.SpawnID(sid);r.ParentAgentID=id.AgentID(parent);r.ChildAgentID=id.AgentID(child);r.RootAgentID=id.AgentID(root);r.TaskKey=taskKey;r.ReservationID=id.BudgetReservationID(resID);r.Status=orchestration.SpawnStatus(status);if err=json.Unmarshal([]byte(auth),&r.Authority);err!=nil{return r,err};if err=json.Unmarshal([]byte(reserved),&r.Reserved);err!=nil{return r,err};r.CreatedAt,err=time.Parse(time.RFC3339Nano,created);if err!=nil{return r,err};r.UpdatedAt,err=time.Parse(time.RFC3339Nano,updated);return r,err}

func (s *Store) Spawn(ctx context.Context, spawnID id.SpawnID)(orchestration.SpawnRecord,error){r,err:=scanSpawn(s.db.QueryRowContext(ctx,`SELECT spawn_id,parent_agent_id,COALESCE(child_agent_id,''),root_agent_id,depth,task_intent,task_key,authority_json,reservation_id,reserved_json,status,created_at,updated_at FROM orchestration_spawns WHERE spawn_id=?`,spawnID.String()));if errors.Is(err,sql.ErrNoRows){return r,errs.Wrap(errs.CodeNotFound,"sqlite.orchestration.spawn","spawn not found",err)};return r,err}
func (s *Store) FindReusableSpawn(ctx context.Context, root id.AgentID,key string)(orchestration.SpawnRecord,bool,error){r,err:=scanSpawn(s.db.QueryRowContext(ctx,`SELECT spawn_id,parent_agent_id,COALESCE(child_agent_id,''),root_agent_id,depth,task_intent,task_key,authority_json,reservation_id,reserved_json,status,created_at,updated_at FROM orchestration_spawns WHERE root_agent_id=? AND task_key=? AND status=? ORDER BY updated_at DESC LIMIT 1`,root.String(),key,string(orchestration.SpawnSettled)));if errors.Is(err,sql.ErrNoRows){return r,false,nil};return r,err==nil,err}
func (s *Store) CountChildren(ctx context.Context,parent id.AgentID)(int,error){var n int;err:=s.db.QueryRowContext(ctx,`SELECT COUNT(*) FROM orchestration_spawns WHERE parent_agent_id=? AND status IN (?,?)`,parent.String(),string(orchestration.SpawnCreated),string(orchestration.SpawnSettled)).Scan(&n);return n,err}
func (s *Store) CountDescendants(ctx context.Context,root id.AgentID)(int,error){var n int;err:=s.db.QueryRowContext(ctx,`WITH RECURSIVE d(agent_id) AS (SELECT child_agent_id FROM orchestration_spawns WHERE parent_agent_id=? AND child_agent_id IS NOT NULL AND status IN (?,?) UNION ALL SELECT s.child_agent_id FROM orchestration_spawns s JOIN d ON s.parent_agent_id=d.agent_id WHERE s.child_agent_id IS NOT NULL AND s.status IN (?,?)) SELECT COUNT(*) FROM d`,root.String(),string(orchestration.SpawnCreated),string(orchestration.SpawnSettled),string(orchestration.SpawnCreated),string(orchestration.SpawnSettled)).Scan(&n);return n,err}
func (s *Store) Descendants(ctx context.Context,root id.AgentID)([]id.AgentID,error){rows,err:=s.db.QueryContext(ctx,`WITH RECURSIVE d(agent_id,depth) AS (SELECT child_agent_id,1 FROM orchestration_spawns WHERE parent_agent_id=? AND child_agent_id IS NOT NULL UNION ALL SELECT s.child_agent_id,d.depth+1 FROM orchestration_spawns s JOIN d ON s.parent_agent_id=d.agent_id WHERE s.child_agent_id IS NOT NULL) SELECT agent_id FROM d ORDER BY depth DESC,agent_id`,root.String());if err!=nil{return nil,err};defer rows.Close();var out []id.AgentID;for rows.Next(){var v string;if err:=rows.Scan(&v);err!=nil{return nil,err};out=append(out,id.AgentID(v))};return out,rows.Err()}

func (s *Store) PutMessage(ctx context.Context,m orchestration.AgentMessage,maxMessages int,maxBytes int64)(bool,error){tx,err:=s.db.BeginTx(ctx,nil);if err!=nil{return false,err};defer tx.Rollback();var exists int;if err=tx.QueryRowContext(ctx,`SELECT COUNT(*) FROM orchestration_messages WHERE message_id=?`,m.ID.String()).Scan(&exists);err!=nil{return false,err};if exists>0{return false,nil};var count int;var bytes int64;if err=tx.QueryRowContext(ctx,`SELECT COUNT(*),COALESCE(SUM(payload_bytes),0) FROM orchestration_messages WHERE to_agent_id=? AND consumed_at IS NULL`,m.To.String()).Scan(&count,&bytes);err!=nil{return false,err};size:=int64(len(m.Inline)+len(m.PayloadRef));if count>=maxMessages||bytes+size>maxBytes{return false,errs.New(errs.CodeResourceExhausted,"sqlite.orchestration.message","mailbox backpressure")};_,err=tx.ExecContext(ctx,`INSERT INTO orchestration_messages(message_id,from_agent_id,to_agent_id,message_type,payload_ref,inline_payload,correlation_id,payload_bytes,created_at) VALUES(?,?,?,?,?,?,?,?,?)`,m.ID.String(),m.From.String(),m.To.String(),string(m.Type),string(m.PayloadRef),m.Inline,m.CorrelationID.String(),size,formatTime(m.CreatedAt));if err!=nil{return false,err};return true,tx.Commit()}
func (s *Store) Mailbox(ctx context.Context,agent id.AgentID,limit int)([]orchestration.AgentMessage,error){rows,err:=s.db.QueryContext(ctx,`SELECT message_id,from_agent_id,to_agent_id,message_type,COALESCE(payload_ref,''),COALESCE(inline_payload,''),COALESCE(correlation_id,''),created_at FROM orchestration_messages WHERE to_agent_id=? AND consumed_at IS NULL ORDER BY CASE message_type WHEN 'result' THEN 0 WHEN 'cancel_request' THEN 1 ELSE 2 END,created_at,message_id LIMIT ?`,agent.String(),limit);if err!=nil{return nil,err};defer rows.Close();var out []orchestration.AgentMessage;for rows.Next(){var m orchestration.AgentMessage;var mid,from,to,typ,ref,cor,created string;if err:=rows.Scan(&mid,&from,&to,&typ,&ref,&m.Inline,&cor,&created);err!=nil{return nil,err};m.ID=id.MessageID(mid);m.From=id.AgentID(from);m.To=id.AgentID(to);m.Type=orchestration.MessageType(typ);m.PayloadRef=objectRef(ref);m.CorrelationID=id.CorrelationID(cor);m.CreatedAt,_=time.Parse(time.RFC3339Nano,created);out=append(out,m)};return out,rows.Err()}
func objectRef(v string) orchestrationObjectRef { return orchestrationObjectRef(v) }
type orchestrationObjectRef = objectstore.Ref
func (s *Store) ConsumeMessage(ctx context.Context,agent id.AgentID,message id.MessageID,at time.Time)(bool,error){res,err:=s.db.ExecContext(ctx,`UPDATE orchestration_messages SET consumed_at=? WHERE message_id=? AND to_agent_id=? AND consumed_at IS NULL`,formatTime(at),message.String(),agent.String());if err!=nil{return false,err};n,_:=res.RowsAffected();return n==1,nil}

func (s *Store) PutWait(ctx context.Context,w orchestration.WaitSpec)error{children,_:=jsonText(w.Children);tx,err:=s.db.BeginTx(ctx,nil);if err!=nil{return err};defer tx.Rollback();if _,err=tx.ExecContext(ctx,`INSERT INTO orchestration_waits(wait_id,parent_agent_id,mode,quorum,failure_policy,children_json,created_at) VALUES(?,?,?,?,?,?,?)`,w.ID.String(),w.ParentID.String(),string(w.Mode),w.Quorum,string(w.Failure),children,formatTime(w.CreatedAt));err!=nil{return err};for _,child:=range w.Children{if _,err=tx.ExecContext(ctx,`INSERT INTO orchestration_wait_edges(wait_id,from_agent_id,to_agent_id) VALUES(?,?,?)`,w.ID.String(),w.ParentID.String(),child.String());err!=nil{return err}};return tx.Commit()}
func (s *Store) DeleteWait(ctx context.Context,w id.WaitID)error{_,err:=s.db.ExecContext(ctx,`DELETE FROM orchestration_waits WHERE wait_id=?`,w.String());return err}
func (s *Store) WaitEdges(ctx context.Context,from id.AgentID)([]id.AgentID,error){rows,err:=s.db.QueryContext(ctx,`SELECT to_agent_id FROM orchestration_wait_edges WHERE from_agent_id=? ORDER BY to_agent_id`,from.String());if err!=nil{return nil,err};defer rows.Close();var out []id.AgentID;for rows.Next(){var v string;if err:=rows.Scan(&v);err!=nil{return nil,err};out=append(out,id.AgentID(v))};return out,rows.Err()}
func (s *Store) WaitsForChild(ctx context.Context,child id.AgentID)([]orchestration.WaitSpec,error){rows,err:=s.db.QueryContext(ctx,`SELECT w.wait_id,w.parent_agent_id,w.mode,w.quorum,w.failure_policy,w.children_json,w.created_at FROM orchestration_waits w JOIN orchestration_wait_edges e ON e.wait_id=w.wait_id WHERE e.to_agent_id=? ORDER BY w.created_at`,child.String());if err!=nil{return nil,err};defer rows.Close();var out []orchestration.WaitSpec;for rows.Next(){var w orchestration.WaitSpec;var wid,pid,mode,failure,children,created string;if err:=rows.Scan(&wid,&pid,&mode,&w.Quorum,&failure,&children,&created);err!=nil{return nil,err};w.ID=id.WaitID(wid);w.ParentID=id.AgentID(pid);w.Mode=orchestration.WaitMode(mode);w.Failure=orchestration.FailurePolicy(failure);_ = json.Unmarshal([]byte(children),&w.Children);w.CreatedAt,_=time.Parse(time.RFC3339Nano,created);out=append(out,w)};return out,rows.Err()}

func (s *Store) PutResult(ctx context.Context,r orchestration.ChildResult)error{body,err:=jsonText(r);if err!=nil{return err};_,err=s.db.ExecContext(ctx,`INSERT INTO orchestration_results(child_agent_id,result_json,completed_at) VALUES(?,?,?) ON CONFLICT(child_agent_id) DO NOTHING`,r.ChildAgentID.String(),body,formatTime(r.CompletedAt));return err}
func (s *Store) Result(ctx context.Context,child id.AgentID)(orchestration.ChildResult,bool,error){var body string;err:=s.db.QueryRowContext(ctx,`SELECT result_json FROM orchestration_results WHERE child_agent_id=?`,child.String()).Scan(&body);if errors.Is(err,sql.ErrNoRows){return orchestration.ChildResult{},false,nil};if err!=nil{return orchestration.ChildResult{},false,err};var r orchestration.ChildResult;err=json.Unmarshal([]byte(body),&r);return r,err==nil,err}

func (s *Store) Enqueue(ctx context.Context,a orchestration.Admission)error{_,err:=s.db.ExecContext(ctx,`INSERT INTO orchestration_admission(agent_id,root_id,priority,enqueued_at,active) VALUES(?,?,?,?,0) ON CONFLICT(agent_id) DO NOTHING`,a.AgentID.String(),a.RootID.String(),a.Priority,formatTime(a.EnqueuedAt));return err}
func (s *Store) DequeueFair(ctx context.Context,globalSlots int,perRootSlots int)([]orchestration.Admission,error){rows,err:=s.db.QueryContext(ctx,`SELECT agent_id,root_id,priority,enqueued_at FROM orchestration_admission WHERE active=0 ORDER BY priority DESC,enqueued_at,root_id,agent_id LIMIT ?`,globalSlots*64);if err!=nil{return nil,err};defer rows.Close();var candidates []orchestration.Admission;for rows.Next(){var a orchestration.Admission;var aid,rid,t string;if err:=rows.Scan(&aid,&rid,&a.Priority,&t);err!=nil{return nil,err};a.AgentID=id.AgentID(aid);a.RootID=id.AgentID(rid);a.EnqueuedAt,_=time.Parse(time.RFC3339Nano,t);candidates=append(candidates,a)};counts:=map[id.AgentID]int{};activeRows,err:=s.db.QueryContext(ctx,`SELECT root_id,COUNT(*) FROM orchestration_admission WHERE active=1 GROUP BY root_id`);if err!=nil{return nil,err};for activeRows.Next(){var root string;var n int;_ = activeRows.Scan(&root,&n);counts[id.AgentID(root)]=n};activeRows.Close();sort.SliceStable(candidates,func(i,j int)bool{return candidates[i].EnqueuedAt.Before(candidates[j].EnqueuedAt)});var picked []orchestration.Admission;used:=map[id.AgentID]bool{};for len(picked)<globalSlots{progress:=false;for _,a:=range candidates{if used[a.AgentID]||counts[a.RootID]>=perRootSlots{continue};used[a.AgentID]=true;counts[a.RootID]++;picked=append(picked,a);progress=true;if len(picked)==globalSlots{break}};if !progress{break}};tx,err:=s.db.BeginTx(ctx,nil);if err!=nil{return nil,err};defer tx.Rollback();now:=formatTime(time.Now().UTC());for _,a:=range picked{if _,err=tx.ExecContext(ctx,`UPDATE orchestration_admission SET active=1,admitted_at=? WHERE agent_id=? AND active=0`,now,a.AgentID.String());err!=nil{return nil,err}};if err=tx.Commit();err!=nil{return nil,err};return picked,nil}
func (s *Store) MarkAdmitted(ctx context.Context,agent id.AgentID,active bool,at time.Time)error{v:=0;if active{v=1};_,err:=s.db.ExecContext(ctx,`UPDATE orchestration_admission SET active=?,admitted_at=? WHERE agent_id=?`,v,formatTime(at),agent.String());return err}
func (s *Store) ActiveByRoot(ctx context.Context,root id.AgentID)(int,error){var n int;err:=s.db.QueryRowContext(ctx,`SELECT COUNT(*) FROM orchestration_admission WHERE root_id=? AND active=1`,root.String()).Scan(&n);return n,err}

var _ orchestration.Store = (*Store)(nil)
